version: "3.9"

services:
  ontime-office-manager:
    container_name: ontime-office-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    restart: unless-stopped
